### ISSUE TITLE
Implementation of Chat Back-end(MVP)

### ISSUE THREAD

**Issue by TheDudeThatCode** [the-coder-dude/ServerMonks-MargDarshan#11]
@the-coder-dude bro we are waiting for you please do it fast !!!

**Comment by the-coder-dude** [comment]
## Socket for Margdarshan App

> Run this at localhost:8080/
> Or try using API hosted on Heroku: https://chat-flutter-pp.herokuapp.com/

* docs: https://socket.io/docs/
