### ISSUE TITLE
Implement Login/SignUp API

### ISSUE THREAD

**Issue by TheDudeThatCode** [the-coder-dude/ServerMonks-MargDarshan#3]
@the-coder-dude please do it ASAP

**Comment by the-coder-dude** [comment]
Setting up the Database right now!

**Comment by the-coder-dude** [comment]
I have implemented Login/Signup API 

> Have a look at readme in backend for more details

**Comment by the-coder-dude** [comment]
📌 I have hosted the API via Heroku on:  https://careerapp-auth.herokuapp.com/

📌 The .env file can found here: https://www.notion.so/env-file-for-Backend-aa2ec480ff6a4f83a85dfb702c0a2840

Use the following to get the responses:

### API Usage:

> POST:
> /adduser

![IMG](https://img.techpowerup.org/200919/for-adduser.jpg)

> POST:
> /authenticate

![IMG](https://img.techpowerup.org/200919/authenticate.jpg)

> GET:
> /getinfo

![IMG](https://img.techpowerup.org/200919/getinfo.jpg)

**Comment by TheDudeThatCode** [comment]
> 📌 I have hosted the API via Heroku on: https://careerapp-auth.herokuapp.com/
> 
> 📌 The .env file can found here: https://www.notion.so/env-file-for-Backend-aa2ec480ff6a4f83a85dfb702c0a2840
> 
> Use the following to get the responses:
> 
> ### API Usage:
> > POST:
> > /adduser
> 
> ![IMG](https://camo.githubusercontent.com/8a9d00c8635bbcaf59d51f8ebe7c5fca023fd9d5/68747470733a2f2f696d672e74656368706f77657275702e6f72672f3230303931392f666f722d616464757365722e6a7067)
> 
> > POST:
> > /authenticate
> 
> ![IMG](https://camo.githubusercontent.com/29f7cb344ce8aa31f504d50abe8191883a32ba56/68747470733a2f2f696d672e74656368706f77657275702e6f72672f3230303931392f61757468656e7469636174652e6a7067)
> 
> > GET:
> > /getinfo
> 
> ![IMG](https://camo.githubusercontent.com/4c7aed40a1885adba4c260aa7cda3e5db13fbd4d/68747470733a2f2f696d672e74656368706f77657275702e6f72672f3230303931392f676574696e666f2e6a7067)

Great sir!!!
