### ISSUE TITLE
Make Wireframes for Login/Signup Screens for Frontend

### ISSUE THREAD

**Issue by the-coder-dude** [the-coder-dude/ServerMonks-MargDarshan#5]
@TheDudeThatCode Provide the wireframes ASAP!!

**Comment by TheDudeThatCode** [comment]
Hey sorry I have made the wireframes for few screens please access them from the below link 

https://freehand.invisionapp.com/freehand/document/mGrw9d1ie


![Hack Chennai](https://user-images.githubusercontent.com/41606999/93658444-3f583480-fa59-11ea-955b-a09af4a339a2.png)

**Comment by TheDudeThatCode** [comment]
@the-coder-dude please don't close this issue I will keep updating here about the wireframes.
