### ISSUE TITLE
Create search API(based on college name)

### ISSUE THREAD

**Issue by TheDudeThatCode** [the-coder-dude/ServerMonks-MargDarshan#9]
@the-coder-dude please finish this asap!!!

**Comment by the-coder-dude** [comment]
Working on it!

**Comment by the-coder-dude** [comment]
* Made full-text search in MongoDB based on the college name

**use GET:**
 > /search/:{college name}
> docs: https://docs.mongodb.com/manual/text-search/

* added Mentor database


📌 commit: https://github.com/the-coder-dude/ServerMonks-MargDarshan/commit/feed9c68007c905197940c91dfe8f92e984e0c58
